/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.uah.vsvmgr.javaflix.gui;
import es.uah.vsvmgr.javaflix.app.Pelicula;
import es.uah.vsvmgr.javaflix.app.Serie;
import java.awt.*;
import java.awt.image.*;
import java.io.*;
import java.util.ArrayList;
import java.util.Arrays;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author marcostuf
 */
public class ControlContenido extends javax.swing.JFrame {

    /**
     * Creates new form ControlContenido
     */
    public ControlContenido() {
        initComponents();
        jComboBox2.setToolTipText("Haga doble click");
        File imagenFile = new File(".\\javaflix.jpg");
        BufferedImage imagen = null;
        try{
        imagen = ImageIO.read(imagenFile);
        }catch (IOException ioe){
        ioe.printStackTrace();
        }
        Image imagenResized = imagen.getScaledInstance(jLabel11.getWidth(), jLabel11.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagenResized);
        jLabel11.setIcon(icono);
        jLabel11.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 650));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 4, 5));
        jPanel1.setMaximumSize(new java.awt.Dimension(950, 650));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 650));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 650));

        jComboBox1.setMaximumSize(new java.awt.Dimension(250, 91));
        jComboBox1.setMinimumSize(new java.awt.Dimension(250, 91));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aplicar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Añadir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField1.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField1.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField2.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField2.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField2.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField3.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField3.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField3.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField4.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField4.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField4.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField5.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField5.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField5.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField6.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField6.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField6.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField7.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField7.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField7.setPreferredSize(new java.awt.Dimension(300, 25));

        jTextField8.setMaximumSize(new java.awt.Dimension(300, 25));
        jTextField8.setMinimumSize(new java.awt.Dimension(300, 25));
        jTextField8.setPreferredSize(new java.awt.Dimension(300, 25));

        jButton4.setText("Ver");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("Titulo");

        jLabel2.setText("Genero");

        jLabel3.setText("Fecha");

        jLabel4.setText("Actores");

        jLabel7.setText("Imagen");

        jLabel8.setText("Sinopsis");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Peliculas", "Series" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel10.setMaximumSize(new java.awt.Dimension(200, 300));
        jLabel10.setMinimumSize(new java.awt.Dimension(200, 300));
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 300));

        jButton5.setText("Eliminar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel11.setMaximumSize(new java.awt.Dimension(191, 100));
        jLabel11.setMinimumSize(new java.awt.Dimension(191, 100));
        jLabel11.setPreferredSize(new java.awt.Dimension(191, 100));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(18, 18, 18)
                                .addComponent(jButton5)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton1)
                                        .addGap(127, 127, 127))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton4)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 142, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(374, 374, 374))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel3)
                                        .addGap(22, 22, 22)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton5)
                            .addComponent(jButton3))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//AÑADIR CONTENIDO
    /**
     * Genera un archivo txt con el nombre de la serie/pelicula como nombre y escribe en el los datos de esta los cuales ha de haber introducido el usuario en los jTextFields correspondientes.
     * Se guardará como pelicula o como serie en funcion de lo que haya seleccionado el administrador en el jComboBox y mostrará un mensaje de error en caso de no haber seleccionado nada
     * @param evt 
     */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex()==1){
            jLabel9.setText("");
            try { 
            PrintWriter data = new PrintWriter(new BufferedWriter(new FileWriter(".\\contenido\\"+jTextField1.getText()+".txt")));
            ArrayList<String> actores = new ArrayList<String>(Arrays.asList(jTextField4.getText().split(",")));
            Pelicula pelicula=new Pelicula(jTextField1.getText(), jTextField8.getText(),jTextField2.getText(), Integer.parseInt(jTextField3.getText()), actores, jTextField7.getText(), Integer.parseInt(jTextField5.getText()), jTextField6.getText());
            data.println(pelicula.toString());
            data.close();
                
            } catch (IOException ioe) {
              System.out.println("Error IO: "+ioe.toString());
}
        }
        else if (jComboBox2.getSelectedIndex()==2) {
            jLabel9.setText("");
                    try { 
            PrintWriter data = new PrintWriter(new BufferedWriter(new FileWriter(".\\contenido\\"+jTextField1.getText()+".txt")));
            ArrayList<String> actores = new ArrayList<String>(Arrays.asList(jTextField4.getText().split(",")));
            Serie serie=new Serie(jTextField1.getText(), jTextField8.getText(),jTextField2.getText(), Integer.parseInt(jTextField3.getText()), actores, jTextField7.getText(), Integer.parseInt(jTextField5.getText()), Integer.parseInt(jTextField6.getText()));
            data.println(serie.toString());
            data.close();
                
            } catch (IOException ioe) {
              System.out.println("Error IO: "+ioe.toString());
}
        }
        else {
        jLabel9.setText("Seleccione una categoria");
        }
        this.dispose();
        ControlContenido controlContenido = new ControlContenido();
        controlContenido.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed
//VOLVER AL MENU ANTERIOR
    /**
     * Lanza el menu de administrador y cierra el actual
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        MenuAdmin menuAdmin = new MenuAdmin();
        menuAdmin.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
//SELECCIONAR TIPO DE CONTENIDO
    /**
     * Permite seleccionar el tipo de contenido que se quiere controlar y lo añade al jComboBox tras filtrar los txt encontrados en la ruta preestablecida (.//contenido//)
     * @param evt 
     */
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        //ADICION DEL CONTENIDO AL DESPLEGABLE Y MOSTRADO DE INFORMACION
        if (jComboBox2.getSelectedIndex()==1){
        jLabel10.setIcon(null);
        File directorio = new File(".\\contenido");
        File[] listaContenido = directorio.listFiles(new FilenameFilter(){
        @Override
        public boolean accept(File directorio, String nombre){
        return nombre.toLowerCase().endsWith(".txt");
        }
        });
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jLabel5.setText("Duracion");
        jLabel6.setText("Director");
        jComboBox1.removeAllItems();
        jComboBox1.addItem("");
        for (File i:listaContenido){
        String cad;
        try{
        FileInputStream fis = new FileInputStream(".\\contenido\\"+i.getName());
        InputStreamReader isr = new InputStreamReader(fis,"ISO-8859-1");
        BufferedReader br = new BufferedReader(isr);
        cad = br.readLine();
        br.close();
        if (cad.split("-")[0].equals("pelicula")){
        jComboBox1.addItem(i.getName().replace(".txt", ""));
        }
        }catch(IOException ioe){}
        }
        }
        else if (jComboBox2.getSelectedIndex()==2) {
        jLabel10.setIcon(null);
        File directorio = new File(".\\contenido");
        File[] listaContenido = directorio.listFiles(new FilenameFilter(){
        @Override
        public boolean accept(File directorio, String nombre){
        return nombre.toLowerCase().endsWith(".txt");
        }
        });
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jComboBox1.removeAllItems();
        jComboBox1.addItem("");
        jTextField5.setVisible(true);
        jTextField6.setVisible(true);
        jLabel5.setText("Temporadas");
        jLabel6.setText("Capitulos");
        for (File i:listaContenido){
        String cad;
        try{
        FileInputStream fis = new FileInputStream(".\\contenido\\"+i.getName());
        InputStreamReader isr = new InputStreamReader(fis,"ISO-8859-1");
        BufferedReader br = new BufferedReader(isr);
        cad = br.readLine();
        br.close();
        if (cad.split("-")[0].equals("serie")){
        jComboBox1.addItem(i.getName().replace(".txt", ""));
        }
        }catch(IOException ioe){}
        }
        }
        else {
        jLabel10.setIcon(null);
        String[] listaContenido=new String[0];
        jComboBox1.removeAllItems();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        jTextField5.setVisible(false);
        jTextField6.setVisible(false);
        jLabel5.setText("");
        jLabel6.setText("");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed
//SELECCIONAR CONTENIDO
    /**
     * Permite seleccionar el contenido concreto a controlar y muestra sus datos en los jTextField correspondientes
     * @param evt 
     */
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        if (!(jComboBox1.getSelectedIndex()==0)){
        String cad;
        try{
        FileInputStream fis = new FileInputStream(".\\contenido\\"+(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()))+".txt");
        InputStreamReader isr = new InputStreamReader(fis,"ISO-8859-1");
        BufferedReader br = new BufferedReader(isr);
        cad = br.readLine();
        br.close();
        String[] cadArray=(cad.split("-"));
        jTextField1.setText(cadArray[1]);
        jTextField2.setText(cadArray[2]);
        jTextField3.setText(cadArray[3]);
        jTextField4.setText(cadArray[4].replace("[", "").replace("]", ""));
        jTextField5.setText(cadArray[5]);
        jTextField6.setText(cadArray[6]);
        jTextField7.setText(cadArray[7]);
        jTextField8.setText(cadArray[8]);
        }catch(IOException ioe){}
        File imagenFile = new File(jTextField7.getText());
        BufferedImage imagen = null;
        try{
        imagen = ImageIO.read(imagenFile);
        }catch (IOException ioe){
        ioe.printStackTrace();
        }
        Image imagenResized = imagen.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagenResized);
        jLabel10.setIcon(icono);
        jLabel10.setVisible(true);
        }
        else {
        jLabel10.setVisible(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed
//APLICAR CAMBIOS EN EL CONTENIDO
    /**
     * Actualiza el archivo txt vinculado al contenido concreto seleccionado en el jComboBox con la informacion introducida en los jTextFields
     * @param evt 
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jComboBox2.getSelectedIndex()==1){
            jLabel9.setText("");
            try { 
            PrintWriter data = new PrintWriter(new BufferedWriter(new FileWriter(".\\contenido\\"+jComboBox1.getItemAt(jComboBox1.getSelectedIndex())+".txt")));
            ArrayList<String> actores = new ArrayList<String>(Arrays.asList(jTextField4.getText().split(",")));
            Pelicula pelicula=new Pelicula(jTextField1.getText(), jTextField8.getText(),jTextField2.getText(), Integer.parseInt(jTextField3.getText()), actores, jTextField7.getText(), Integer.parseInt(jTextField5.getText()), jTextField6.getText());
            data.println(pelicula.toString());
            data.close();
            File fileOrig = new File(".\\contenido\\"+jComboBox1.getItemAt(jComboBox1.getSelectedIndex())+".txt");
            File fileNuev = new File(".\\contenido\\"+jTextField1.getText()+".txt");
            fileOrig.renameTo(fileNuev);
            this.dispose();
            ControlContenido controlContenido = new ControlContenido();
            controlContenido.setVisible(true);
                
            } catch (IOException ioe) {
              System.out.println("Error IO: "+ioe.toString());
}
        }
        else if (jComboBox2.getSelectedIndex()==2) {
            jLabel9.setText("");
                    try { 
            PrintWriter data = new PrintWriter(new BufferedWriter(new FileWriter(".\\contenido\\"+jComboBox1.getItemAt(jComboBox1.getSelectedIndex())+".txt")));
            ArrayList<String> actores = new ArrayList<String>(Arrays.asList(jTextField4.getText().split(",")));
            Serie serie=new Serie(jTextField1.getText(), jTextField8.getText(),jTextField2.getText(), Integer.parseInt(jTextField3.getText()), actores, jTextField7.getText(), Integer.parseInt(jTextField5.getText()), Integer.parseInt(jTextField6.getText()));
            data.println(serie.toString());
            data.close();
            File fileOrig = new File(".\\contenido\\"+jComboBox1.getItemAt(jComboBox1.getSelectedIndex())+".txt");
            File fileNuev = new File(".\\contenido\\"+jTextField1.getText()+".txt");
            fileOrig.renameTo(fileNuev);
            this.dispose();
            ControlContenido controlContenido = new ControlContenido();
            controlContenido.setVisible(true);
                
            } catch (IOException ioe) {
              System.out.println("Error IO: "+ioe.toString());
}
        }
       else {
            jLabel9.setText("Seleccione un tipo de contenido");
        }
    }//GEN-LAST:event_jButton2ActionPerformed
//VER LA IMAGEN ESPECIFICADA
    /**
     * Muestra la imagen especificada en el jTextField sin alterar la guardada en el archivo txt
     * @param evt 
     */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        File imagenFile = new File(jTextField7.getText());
        BufferedImage imagen = null;
        try{
        imagen = ImageIO.read(imagenFile);
        }catch (IOException ioe){
        ioe.printStackTrace();
        }
        Image imagenResized = imagen.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon icono = new ImageIcon(imagenResized);
        jLabel10.setIcon(icono);
        jLabel10.setVisible(true);
        
    }//GEN-LAST:event_jButton4ActionPerformed
//ELIMINAR CONTENIDO
    /**
     * Elimina el archivo txt vinculado al contenido concreto seleccionado en el jComboBox
     * @param evt 
     */
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        if (!(jComboBox1.getSelectedIndex()==0)){
        File file = new File(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
        file.delete();
        this.dispose();
        ControlContenido controlContenido = new ControlContenido();
        controlContenido.setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ControlContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ControlContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ControlContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlContenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ControlContenido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
